# Generated by Django 4.2.1 on 2023-05-15 15:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Patient",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("gender", models.CharField(max_length=6)),
                ("age", models.PositiveIntegerField()),
                ("hypertension", models.IntegerField()),
                ("heart_disease", models.IntegerField()),
                ("smoking_history", models.CharField(max_length=11)),
                ("bmi", models.FloatField()),
                ("HbA1c_level", models.FloatField()),
                ("blood_glucose_level", models.IntegerField()),
                ("diabetes", models.IntegerField()),
            ],
        ),
    ]
